name: Generate Zip File

on:
  push:
    paths:
      - 'data/**.json'
      - 'resources/**'
      - '!resources/genshin_resources.zip'
  workflow_dispatch:

jobs:
  GenerateZipFile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Set up Git LFS
      run: |
        git lfs install --local
        git config lfs.fetchexclude "resources/**/*.zip"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8

    - name: Install Package
      run: poetry install

    - name: Run Generate Script
      run: poetry run python generate.py

    - name: Show Dir
      run: |
        ls
        cd resources
        echo "Dir Resources:"
        ls
        cd ..
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: "pulled_files"
        name: Release "${{ github.event.inputs.docker_images }}"
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          '*.json'
          '*.zip'
          '!resources/genshin_resources.zip'

          
    - name: Commit changes
      run: |
        git lfs track "*.zip"
        git add '*.json' '*.zip'
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m ':wrench: 更新文件'
        git push origin HEAD:refs/heads/master
